# This document was created by following this: https://www.netlifycms.org/docs/add-to-your-site/

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# The publish_mode option allows you to enable “Editorial Workflow” mode for more control over the
# content publishing phases. All unpublished entries will be arranged in a board according to their
# status, and they can be further reviewed and edited before going live. More information:
# https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Hugo stores its static files in a subfolder, so we have to set `public_folder` to specify where
# the assets can be found on the public site.
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Callout, name: title, widget: text}
          - label: "Feature: who we are"
            name: "feature-who"
            widget: "object"
            fields:
              - {label: "Image", name: "feature-image", widget: "image"}
              - {label: "Header", name: "feature-header", widget: "string"}
              - {label: "Content", name: "feature-content", widget: "text"}
          - label: "Feature: what's democratic socialism"
            name: "feature-what"
            widget: "object"
            fields:
              - {label: "Image", name: "feature-image", widget: "image"}
              - {label: "Header", name: "feature-header", widget: "string"}
              - {label: "Content", name: "feature-content", widget: "text"}
          - label: "Feature: upcoming events"
            name: "feature-events"
            widget: "object"
            fields:
              - {label: "Image", name: "feature-image", widget: "image"}
              - {label: "Header", name: "feature-header", widget: "string"}
              - {label: "Content", name: "feature-content", widget: "text"}
          - label: "Feature: join"
            name: "feature-join"
            widget: "object"
            fields:
              - {label: "Image", name: "feature-image", widget: "image"}
              - {label: "Header", name: "feature-header", widget: "string"}
              - {label: "Content", name: "feature-content", widget: "text"}

      # - file: "site/content/about/_index.md"
      #   label: "Who we are"
      #   name: "about"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Logo, name: logo, widget: image}
      #     - {label: Body, name: body, widget: markdown}
      #     - label: Contact Entries
      #       name: contact_entries
      #       widget: list
      #       fields:
      #         - label: Heading
      #           name: heading
      #           widget: string
      #         - label: Text
      #           name: text
      #           widget: text
      # - file: "site/content/what-is-democratic-socialism/_index.md"
      #   label: "What is democratic socialism"
      #   name: "what-is-democratic-socialism"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Image, name: image, widget: image}
      #     - {label: Heading, name: heading, widget: string}
      #     - {label: Description, name: description, widget: string}
      #     - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      #     - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      #     - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      #     - {label: Full_image, name: full_image, widget: image}
      #     - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      # - file: "site/content/join/_index.md"
      #   label: "Join us"
      #   name: "join"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Image, name: image, widget: image}
      #     - label: Values
      #       name: values
      #       widget: list
      #       fields:
      #         - {label: Heading, name: heading, widget: string}
      #         - {label: Text, name: text, widget: text}
      #         - {label: Image, name: imageUrl, widget: image}
