# This document was created by following this: https://www.netlifycms.org/docs/add-to-your-site/

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# The publish_mode option allows you to enable “Editorial Workflow” mode for more control over the
# content publishing phases. All unpublished entries will be arranged in a board according to their
# status, and they can be further reviewed and edited before going live. More information:
# https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Hugo stores its static files in a subfolder, so we have to set `public_folder` to specify where
# the assets can be found on the public site.
media_folder: "static/assets/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
  - label: "Test"
    name: "test"
    folder: "content/test"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

